#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-projec-1-bff
  annotations:
    github.com/project-slug: djajcevic-idp/demo-projec-1-bff-acs
    backstage.io/environment: dev
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=demo-projec-1-bff-bff'
    argocd/app-name: demo-projec-1-bff
    sonarqube.org/project-key: default/demo-projec-1-bff
  tags:
    - java
  links:
    - url: https://demo-projec-1-bff.apps.idp.dhl.com/api
      title: API
      icon: star
spec:
  type: service
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/demo-projec-1-bff-acr
  providesApis:
    - demo-projec-1-bff
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-projec-1-bff
spec:
  type: rest
  lifecycle: deprecated
  owner: demo-team
  definition:
    $text: https://demo-projec-1-bff.apps.idp.dhl.com/api/api-docs